package com.gffny.leaderboard.model;

import java.util.List;
import java.util.Map;

public interface ICompetition {

	public String getCompetitionName();
	
	public String getCompetitionDate();
	
	public String getCompetitionFirstTeeTime();
	
	public String getCompetitionTypeName();
	
	public List<ICompetitionRound> getCompetitionRoundList(); //each round will have enclosed data grouping list & tee time may be only one round for certain comp. types
	
	public void addCompetitionRound(ICompetitionRound round);
	
	public interface ICompetitionRound {
		
		public String getRoundName();
		
		public String getRoundDate();
		
		public String getRoundFirstTeeTime();
		
		public List<IGolfGroup> getGroupList();
		
		public Map<IGolfGroup, String> getTeeTimeMap();

		public String getGroupTeeTime(IGolfGroup group);

	}
	
	public interface IGolfGroup {

		public String getGroupName(); //generated by competition name, date, and order number (i.e. BLOOD_N_BANDAGES_PDWC_MONDAY_GRP1)
		public String getGroupType(); //pair, threeball, three person team, fourball, two pair, four person team

		public List<IGolfer> getGolferList(); //TODO is order important? can we insure its' integrity? (i.e. first two out are pair one, and last two out are pair two?)

	}
}
